# Generated by Django 5.1.4 on 2025-07-23 18:19

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='عنوان')),
                ('url_title', models.CharField(blank=True, db_index=True, editable=False, max_length=300, verbose_name='عنوان در url')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='تصویر دسته\u200cبندی')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(verbose_name='حذف شده / نشده')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='ProductListPageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان صفحه')),
                ('background_image', models.ImageField(upload_to='product-list-bg/', verbose_name='تصویر پس\u200cزمینه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
            ],
            options={
                'verbose_name': 'تنظیمات صفحه لیست محصولات',
                'verbose_name_plural': 'تنظیمات صفحه لیست محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductOptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام گزینه (مثل رنگ نما)')),
            ],
            options={
                'verbose_name': 'نوع گزینه',
                'verbose_name_plural': 'انواع گزینه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='نام محصول')),
                ('product_quantity', models.BooleanField(default=True, null=True, verbose_name='موجودی محصول')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products', verbose_name='تصویر محصول')),
                ('discount_price', models.IntegerField(null=True, verbose_name='قیمت تخفیف')),
                ('price', models.IntegerField(verbose_name='قیمت اصلی')),
                ('cheque_price', models.IntegerField(blank=True, null=True, verbose_name='قیمت چکی')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, default='', max_length=200, unique=True, verbose_name='عنوان در url')),
                ('short_description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیح کوتاه')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیح کامل')),
                ('badge_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='متن بج (نشان)')),
                ('is_new', models.BooleanField(default=False, help_text='اگر این تیک فعال باشد، بج "جدید" زیر بج اصلی نمایش داده می\u200cشود.', verbose_name='محصول جدید؟')),
                ('is_discount_active', models.BooleanField(default=False, help_text='اگر مایل به نمایش این تخفیف در سایت هستید این تیک را بزنید.', verbose_name='تخفیف فعال است؟')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(verbose_name='حذف شده / نشده')),
                ('has_custom_options', models.BooleanField(default=False, verbose_name='آیا این محصول نیاز به مشخصات انتخابی دارد؟')),
                ('category', models.ManyToManyField(related_name='product_categories', to='product_module.productcategory', verbose_name='دسته بندی ها')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified_buyer', models.BooleanField(default=False, verbose_name='خریدار تایید شده؟')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product_module.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر محصول',
                'verbose_name_plural': 'نظرات محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='مقدار گزینه')),
                ('option_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='product_module.productoptiontype')),
            ],
            options={
                'verbose_name': 'مقدار گزینه',
                'verbose_name_plural': 'مقادیر گزینه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ProductSelectableOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_values', models.ManyToManyField(to='product_module.productoptionvalue', verbose_name='مقادیر مجاز')),
                ('option_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.productoptiontype', verbose_name='نوع گزینه')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selectable_options', to='product_module.product')),
            ],
            options={
                'verbose_name': 'گزینه انتخابی محصول',
                'verbose_name_plural': 'گزینه\u200cهای انتخابی محصول',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='product_module.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'علاقه\u200cمندی',
                'verbose_name_plural': 'لیست علاقه\u200cمندی\u200cها',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
