# Generated by Django 5.1.4 on 2025-09-10 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام افزونه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('additional_cost', models.PositiveIntegerField(verbose_name='هزینه اضافی (ریال)')),
                ('is_required', models.BooleanField(default=False, verbose_name='اجباری است؟')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='product_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'افزونه محصول',
                'verbose_name_plural': 'افزونه\u200cهای محصولات',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
