# Generated by Django 5.1.4 on 2025-09-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_productaddon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productaddon',
            name='additional_cost',
            field=models.PositiveIntegerField(verbose_name='هزینه اضافی'),
        ),
    ]
