# Generated by Django 5.1.4 on 2025-09-10 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_alter_productaddon_additional_cost'),
    ]

    operations = [
        # These models already exist in the database from earlier migrations
        # This migration is kept for consistency but performs no operations
        migrations.RunSQL(
            sql="SELECT 1;",  # No-op SQL
            reverse_sql="SELECT 1;",  # No-op reverse SQL
        ),
    ]
