# Generated by Django 5.1.4 on 2025-09-12 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_auto_20250910_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام گزینه (مثل رنگ نما)')),
            ],
            options={
                'verbose_name': 'نوع گزینه',
                'verbose_name_plural': 'انواع گزینه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ProductOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='مقدار گزینه')),
                ('option_type', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='values', to='product_module.productoptiontype')),
            ],
            options={
                'verbose_name': 'مقدار گزینه',
                'verbose_name_plural': 'مقادیر گزینه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ProductSelectableOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_values', models.ManyToManyField(to='product_module.productoptionvalue', verbose_name='مقادیر مجاز')),
                ('option_type', models.ForeignKey(on_delete=models.deletion.CASCADE, to='product_module.productoptiontype', verbose_name='نوع گزینه')),
                ('product', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='selectable_options', to='product_module.product')),
            ],
            options={
                'verbose_name': 'گزینه انتخابی محصول',
                'verbose_name_plural': 'گزینه\u200cهای انتخابی محصول',
            },
        ),
    ]
