# Generated by Django 5.1.4 on 2025-09-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='selected_addons',
            field=models.JSONField(blank=True, default=list, verbose_name='افزونه\u200cهای انتخاب شده'),
        ),
    ]
