# Generated by Django 5.1.4 on 2025-09-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0003_orderdetail_selected_addons'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='selected_options',
            field=models.JSONField(blank=True, default=dict, verbose_name='گزینه\u200cهای انتخاب شده'),
        ),
    ]
