# Generated by Django 5.1.4 on 2025-04-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_product', models.URLField(max_length=500, null=True, verbose_name='لینک دسته بندی ')),
                ('caption', models.CharField(max_length=200, verbose_name='عنوان دسته بندی ')),
                ('image', models.ImageField(upload_to='images/home_category', verbose_name='تصویر دسته بندی ')),
                ('is_active', models.BooleanField(null=True, verbose_name='فعال/غیر فعال ')),
            ],
            options={
                'verbose_name': 'دسته بندی صفحه اصلی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='InstagramFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('instagram_feed_pics', models.ImageField(null=True, upload_to='images/instagram_feed', verbose_name='تصاویر اسلایدر اینستاگرام ')),
                ('is_active', models.BooleanField(null=True, verbose_name='فعال/غیر فعال')),
            ],
            options={
                'verbose_name': 'تصویر اسلایدر اینستاگرام    ',
                'verbose_name_plural': 'تصاویر بخش اینستاگرام',
            },
        ),
        migrations.CreateModel(
            name='InstallmentsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installments_sale', models.TextField(null=True, verbose_name='متن شرایط اقساط ')),
                ('installments_sale_image', models.ImageField(null=True, upload_to='images/installments_directory', verbose_name='تصویر شرایط  اقساط ')),
                ('is_active', models.BooleanField(null=True, verbose_name='فعال/ غیر فعال')),
            ],
            options={
                'verbose_name': 'تنظیمات اقساطی',
                'verbose_name_plural': ' صفحه شرایط اقساط ',
            },
        ),
        migrations.CreateModel(
            name='MonthSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.ImageField(null=True, upload_to='images/month-sale')),
                ('title', models.CharField(max_length=20, verbose_name='عنوان محصول')),
                ('description', models.TextField(max_length=350, verbose_name='توضیحات محصول منتخب ماه')),
                ('url', models.URLField(blank=True, max_length=400, null=True, verbose_name='لینک محصول')),
                ('image', models.ImageField(upload_to='images/month-sale', verbose_name='تصویر محصول')),
                ('is_active', models.BooleanField(verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'محصول انتخابی ',
                'verbose_name_plural': 'محصول انتخابی ماه',
            },
        ),
        migrations.CreateModel(
            name='SiteHeaderDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(db_index=True, max_length=100, null=True, verbose_name='فیلد اطلاع رسانی تخفیف سایت ')),
                ('is_active', models.BooleanField(null=True, verbose_name='فعال/غیر فعال ')),
            ],
            options={
                'verbose_name': 'تخفیف سایت',
                'verbose_name_plural': 'تخفیف هدر سایت',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='نام سایت')),
                ('site_url', models.CharField(max_length=200, verbose_name='دامنه سایت ')),
                ('address', models.CharField(max_length=200, verbose_name='آدرس  ')),
                ('instagram_address', models.CharField(max_length=200, null=True, verbose_name='آدرس پیج اینستاگرام ')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='شماره تماس   ')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='ایمیل  ')),
                ('copyright', models.TextField(verbose_name='متن کپی رایت  ')),
                ('site_logo', models.ImageField(upload_to='images/site-settings/', verbose_name='لوگو سایت  ')),
                ('about_us_text_header', models.CharField(max_length=100, null=True, verbose_name='عنوان اصلی درباره ما')),
                ('about_us_text', models.TextField(verbose_name='درباره ما  ')),
                ('about_us_sec_text_first', models.CharField(max_length=100, null=True, verbose_name='عنوان اول متن پایین درباره ما')),
                ('about_us_sec_text_second', models.CharField(max_length=100, null=True, verbose_name='عنوان دوم متن پایین درباره ما')),
                ('about_us_sec_text_third', models.CharField(max_length=100, null=True, verbose_name='عنوان سوم متن پایین درباره ما')),
                ('about_us_sec_textfield_first', models.TextField(null=True, verbose_name=' متن اول پایین درباره ما')),
                ('about_us_sec_textfield_second', models.TextField(null=True, verbose_name=' متن دوم پایین درباره ما')),
                ('about_us_sec_textfield_third', models.TextField(null=True, verbose_name=' متن سوم پایین درباره ما')),
                ('about_us_image', models.ImageField(null=True, upload_to='images/site-settings/', verbose_name='تصویر قسمت درباره ما')),
                ('is_main_settings', models.BooleanField(verbose_name='تنظیمات اصلی ')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='عنوان')),
                ('url', models.URLField(max_length=500, null=True, verbose_name='لینک')),
                ('image', models.ImageField(upload_to='images/sliders', verbose_name='تصویر اسلایدر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر ها',
            },
        ),
    ]
