# Generated by Django 5.1.4 on 2025-04-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageCategories',
        ),
        migrations.DeleteModel(
            name='InstagramFeed',
        ),
        migrations.DeleteModel(
            name='InstallmentsPage',
        ),
        migrations.DeleteModel(
            name='MonthSale',
        ),
        migrations.DeleteModel(
            name='SiteHeaderDiscount',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_us_image',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_us_sec_text_first',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_us_sec_text_second',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_us_sec_text_third',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_us_sec_textfield_first',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_us_sec_textfield_second',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_us_sec_textfield_third',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_us_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_us_text_header',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='address',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='copyright',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='is_main_settings',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_logo',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_url',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='business_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس کسب\u200cوکار'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='لینک تلگرام'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره واتساپ'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس پیج اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='شماره تماس'),
        ),
    ]
