# Generated by Django 5.1.4 on 2025-04-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_delete_homepagecategories_delete_instagramfeed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/site-settings/', verbose_name='لوگو سایت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام سایت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='دامنه سایت'),
        ),
    ]
