# Generated by Django 5.1.4 on 2025-04-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_sitesettings_site_logo_sitesettings_site_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='is_main_settings',
            field=models.BooleanField(default=False, verbose_name='تنظیمات اصلی'),
        ),
    ]
