# Generated by Django 5.1.4 on 2025-04-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_sitesettings_is_main_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='copyright',
            field=models.TextField(blank=True, null=True, verbose_name='متن کپی رایت'),
        ),
    ]
