# Generated by Django 5.1.4 on 2025-04-19 15:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-published_at'], 'verbose_name': 'وبلاگ', 'verbose_name_plural': 'وبلاگ\u200cها'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='full_description',
            field=models.TextField(verbose_name='توضیح کامل'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='blogs/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=models.TextField(verbose_name='توضیح کوتاه'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
    ]
