# Generated by Django 5.1.4 on 2025-09-12 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userimageupload',
            options={'verbose_name': 'تصاویر ارسالی کاربران', 'verbose_name_plural': 'تصاویر ارسالی کاربران'},
        ),
    ]
