# Generated by Django 5.1.4 on 2025-04-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=300, verbose_name='ایمیل')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('admin_response', models.TextField(blank=True, null=True, verbose_name='پاسخ ادمین ')),
                ('seen_by_admin', models.BooleanField(null=True, verbose_name='خوانده شده توسط ادمین')),
            ],
            options={
                'verbose_name': 'تماس با ما ',
                'verbose_name_plural': 'لیست تماس با ما  ',
            },
        ),
        migrations.CreateModel(
            name='ContactUsPageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_description', models.CharField(max_length=300, verbose_name='توضیحات مربوط به صفحه تماس با ما ')),
                ('address_info', models.CharField(max_length=100, verbose_name='آدرس مربوط به صفحه تماس با ما ')),
                ('phone_info', models.CharField(max_length=100, verbose_name='شماره تماس مربوط به صفحه تماس با ما ')),
                ('email_info', models.CharField(max_length=100, verbose_name='ایمیل مربوط به صفحه تماس با ما ')),
            ],
            options={
                'verbose_name': 'اطلاعات تماس با ما  ',
                'verbose_name_plural': 'اطلاعات کنار صفحه تماس با ما   ',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
