# Generated by Django 5.1.4 on 2025-04-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='admin_response',
        ),
    ]
