# Generated by Django 5.1.4 on 2025-04-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_remove_contactus_admin_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='email',
        ),
        migrations.AddField(
            model_name='contactus',
            name='mobile',
            field=models.CharField(default=True, max_length=20, null=True, verbose_name='شماره موبایل'),
        ),
    ]
