# Generated by Django 5.1.4 on 2025-04-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0003_remove_contactus_email_contactus_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='mobile',
            field=models.CharField(default=False, max_length=20, null=True, verbose_name='شماره موبایل'),
        ),
    ]
