# Generated by Django 5.1.4 on 2025-07-23 18:19

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='department_cards/', verbose_name='تصویر')),
                ('link', models.URLField(default='shop.html', verbose_name='لینک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
            ],
            options={
                'verbose_name': 'بخش',
                'verbose_name_plural': 'بخش ها',
            },
        ),
        migrations.CreateModel(
            name='FurnitureMainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام دسته اصلی')),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
            ],
            options={
                'verbose_name': 'دسته اصلی مبلمان',
                'verbose_name_plural': 'دسته\u200cهای اصلی مبلمان',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeVideoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان اصلی')),
                ('subtitle', models.CharField(max_length=255, verbose_name='زیرعنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('video_file', models.FileField(upload_to='home/video/', verbose_name='فایل ویدیو')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
            ],
            options={
                'verbose_name': 'بخش ویدیویی صفحه اصلی',
                'verbose_name_plural': 'بخش\u200cهای ویدیویی صفحه اصلی',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان صفحه روش\u200cهای پرداخت')),
                ('content', ckeditor.fields.RichTextField(verbose_name='محتوای صفحه روش\u200cهای پرداخت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
            ],
            options={
                'verbose_name': 'صفحه روش\u200cهای پرداخت',
                'verbose_name_plural': 'صفحات روش\u200cهای پرداخت',
            },
        ),
        migrations.CreateModel(
            name='RefundTermsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان صفحه شرایط بازگشت')),
                ('content', ckeditor.fields.RichTextField(verbose_name='محتوای صفحه شرایط بازگشت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
            ],
            options={
                'verbose_name': 'صفحه شرایط بازگشت',
                'verbose_name_plural': 'صفحات شرایط بازگشت',
            },
        ),
        migrations.CreateModel(
            name='RulesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان صفحه')),
                ('content', ckeditor.fields.RichTextField(verbose_name='محتوای قوانین')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
            ],
            options={
                'verbose_name': 'صفحه قوانین',
                'verbose_name_plural': 'صفحات قوانین',
            },
        ),
        migrations.CreateModel(
            name='ShipmentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان صفحه ارسال')),
                ('content', ckeditor.fields.RichTextField(verbose_name='محتوای صفحه ارسال')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
            ],
            options={
                'verbose_name': 'صفحه ارسال',
                'verbose_name_plural': 'صفحات ارسال',
            },
        ),
        migrations.CreateModel(
            name='FurnitureSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام زیر\u200cدسته')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='home_module.furnituremaincategory', verbose_name='دسته اصلی')),
                ('products', models.ManyToManyField(limit_choices_to={'is_active': True, 'is_delete': False}, to='product_module.product', verbose_name='محصولات')),
            ],
            options={
                'verbose_name': 'زیر\u200cدسته مبلمان',
                'verbose_name_plural': 'زیر\u200cدسته\u200cهای مبلمان',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HotDealProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=1, verbose_name='اولویت نمایش')),
                ('countdown_expiry', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان پیشنهاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن پیشنهاد شگفت\u200cانگیز')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'محصول شگفت\u200cانگیز',
                'verbose_name_plural': 'محصولات شگفت\u200cانگیز',
                'ordering': ['priority'],
            },
        ),
    ]
