# Generated by Django 5.1.4 on 2025-09-09 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0001_initial'),
        ('product_module', '0002_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentcard',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.productcategory', verbose_name='دسته\u200cبندی مرتبط'),
        ),
    ]
