# Generated by Django 5.1.4 on 2025-04-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='check_purchase_credit',
            field=models.PositiveIntegerField(default=0, verbose_name='اعتبار خرید چکی (تومان)'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_check_purchase_permission',
            field=models.BooleanField(default=False, verbose_name='دارای مجوز خرید چکی؟'),
        ),
    ]
